# Generated by Django 5.2.11 on 2026-02-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_alta", models.DateField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=5, unique=True)),
                ("descripcion", models.CharField(max_length=100)),
                ("color_fondo", models.CharField(default="#FFFFFF", max_length=7)),
                ("color_texto", models.CharField(default="#000000", max_length=7)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estado de Asistencia",
                "verbose_name_plural": "Estados de Asistencia",
                "ordering": ["orden", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="asistencia.empleado",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="asistencia.estadoasistencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Asistencia",
                "verbose_name_plural": "Registros de Asistencia",
                "unique_together": {("empleado", "fecha")},
            },
        ),
    ]
